<a href="https://colab.research.google.com/github/amicuscertus/Colab001/blob/master/colon001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = [1, 2, 3, 4, 5]
print(type(a))

<class 'list'>


In [2]:
a[2:4]

[3, 4]

In [3]:
a[:4]

[1, 2, 3, 4]

In [4]:
a[2:]

[3, 4, 5]

In [5]:
a[:]

[1, 2, 3, 4, 5]

In [6]:
b = 'python_is_cool'
print(type(b))

<class 'str'>


In [7]:
b[2:4]

'th'

In [8]:
b[:4]

'pyth'

In [9]:
b[2:]

'thon_is_cool'

In [10]:
b[:]

'python_is_cool'

In [11]:
import numpy as np
c = np.arange(10, 23, 3)
print(type(c))
print(c)

<class 'numpy.ndarray'>
[10 13 16 19 22]


In [12]:
c[2:4]

array([16, 19])

In [13]:
c[:4]

array([10, 13, 16, 19])

In [14]:
c[2:]

array([16, 19, 22])

In [15]:
c[:]

array([10, 13, 16, 19, 22])

In [16]:
d = np.arange(0,12).reshape(4,3)
print(type(d))
print(d.shape)
print(d)

<class 'numpy.ndarray'>
(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
print(d[2,1])

7


In [18]:
print(d[:,1])

[ 1  4  7 10]


In [19]:
print(d[2,:])

[6 7 8]


In [20]:
print(d[:,:])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [21]:
print(d[:,])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
print(d[1:3,])

[[3 4 5]
 [6 7 8]]


In [23]:
print(d[:,1:3])

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


In [24]:
e = np.arange(60).reshape(5,4,3)
print(e.shape)
print(e)

(5, 4, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]

 [[48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


In [25]:
print(e[3,2,1])

43


In [26]:
print(e[:,:,0])

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [36 39 42 45]
 [48 51 54 57]]
